# This code creates a new RPKM file by filtering the data using DoGs.

# Define the paths to the RPKM and DoGs files.
rpkm_file = "RPKM_file.txt"  # Specify the path to the RPKM file generated by RPKM.py code.
dogs_file = "ARTDeco_Total_dog_annotation.bed"  # Specify the path to the DoG file.
new_rpkm = "RPKM_file_af2.txt"  # Specify the name and path for the output file.

# Open the DoG file, RPKM file, and the new RPKM file for reading and writing, respectively.
with open(dogs_file, "r") as dogs, open(rpkm_file, "r") as rpkms, open(new_rpkm, "w") as nrpkm:
    dogs_ids = []  # Initialize an empty list to store DoG IDs.

    # Iterate through each line in the DoG file.
    for dog in dogs:
        # Extract the DoG ID from the fourth tab-separated field in the line.
        dog_id = dog.strip().split("\t")[3]
        dogs_ids.append(dog_id)  # Add the extracted DoG ID to the list.

    # Write the header from the RPKM file to the new RPKM file.
    nrpkm.write(rpkms.readline())

    # Iterate through each line in the RPKM file.
    for rpkm in rpkms:
        # Extract the RPKM ID from the first tab-separated field in the line.
        rpkm_id = rpkm.strip().split("\t")[0]
        # Check if the RPKM ID exists in the list of DoG IDs.
        if rpkm_id in dogs_ids:
            # If it exists, write the RPKM line to the new RPKM file.
            nrpkm.write(rpkm)
